--- #YAML:1.0
name:                Audio-SndFile
version:             0.07
abstract:            Portable reading and writing of sound files
license:             ~
author:              
    - Joost Diepenmaat <jdiepen@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
